@echo off
copy imag0103.txt+imag0103.pcx lpt2 /b
pause
copy imag0104.txt+imag0104.pcx lpt2 /b
pause
copy imag0105.txt+imag0105.pcx lpt2 /b
pause
copy imag0212.txt+imag0212.pcx lpt2 /b
pause
copy imag0213.txt+imag0213.pcx lpt2 /b
pause
copy imag0504.txt+imag0504.pcx lpt2 /b
pause
copy imag0505.txt+imag0505.pcx lpt2 /b
pause
copy imag0506.txt+imag0506.pcx lpt2 /b
pause
copy imag0607.txt+imag0607.pcx lpt2 /b
pause
copy imag0608.txt+imag0608.pcx lpt2 /b
pause
copy imag0609.txt+imag0609.pcx lpt2 /b
pause
echo.
echo Download concluido!
