CREATE ALIAS mgadm   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgadt   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgcex   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgcld   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgdis   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgfis   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgind   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mginv   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmfg   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmnt   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmrp   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmp    FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgscm   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgven   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgrac   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mguni   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgtmp   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS movadm  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movdis  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movfis  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movind  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movmfg  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movmnt  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movmrp  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movrac  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS wmovdis FOR DATABASE mgmov NO-ERROR.

IF SEARCH("scripts/manutencao.lck") <> ? THEN DO:
   MESSAGE "Prezado Usu rio:" SKIP(2)
           "O Sistema est  em Manuten‡Æo." SKIP
           "Por favor, aguarde um instante." SKIP(2)
           "Equipe de Inform tica."
           VIEW-AS ALERT-BOX INFO.
   QUIT.
END.

RUN sztools\sztools.r.

QUIT.
