DEF VAR i-handle AS INT.

PROCEDURE FindWindowA EXTERNAL "USER32.DLL":
    DEFINE INPUT  PARAMETER intClassName AS LONG.
    DEFINE INPUT  PARAMETER chrCaption   AS CHARACTER.
    DEFINE RETURN PARAMETER intHandle    AS LONG.
END PROCEDURE.

RUN FindWindowA (0, "Microsoft Excel", OUTPUT i-handle).

MESSAGE i-handle
    VIEW-AS ALERT-BOX INFO BUTTONS OK.
