
/*------------------------------------------------------------------------
    File        : ETipoFrete
    Purpose     : 
    Syntax      : 
    Description : Tipos de Frete 
    Author(s)   : administrator
    Created     : Thu Apr 10 16:05:25 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum RegraNegocio.Frete.ETipoFrete :  

    define enum CIF 
                FOB 
                CIF-PARCIAL .

end enum.