
/*------------------------------------------------------------------------
    File        : ESistemaOperacional
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : user
    Created     : Tue Apr 15 14:16:17 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum Comum.ESistemaOperacional flags :  

    define enum Windows 
                Linux 
                Mac 
                Android .

end enum.