
/*------------------------------------------------------------------------
    File        : ESitSincr
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : tadeu.parreiras
    Created     : Wed May 07 11:21:59 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

ENUM Comum.ESitSincr :  

    DEFINE ENUM sem-acao 
                encontrou 
                cadastrou
                erro-negocio .

END ENUM.