
/*------------------------------------------------------------------------
    File        : ETipoDadoEnvioAPI
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : user
    Created     : Tue Apr 15 09:50:33 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum ConsumoAPI.ETipoDadoAPI :  

    define enum JSON      = 1 
                XML       = 2  
                TEXTO     = 4
                BINARIO   = 8
                MULTIPART = 16
                HTML      = 32
                CSS       = 64
                JAVASCRIPT=128
                CSV       =256
                PDF       =512
                ZIP       =1024
                IMAGEM    =2048
                AUDIO     =4096
                VIDEO     =8192
                
                .

end enum.