
/*------------------------------------------------------------------------
    File        : ETipoAplicQueryString
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : user
    Created     : Sat Apr 19 13:40:01 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum ConsumoAPI.ETipoAplicQueryString flags :  

    define enum URL 
                Arquivo .

end enum.