
/*------------------------------------------------------------------------
    File        : IQueryParam
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : user
    Created     : Tue Apr 15 08:57:48 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
using Comum.IChaveValor from propath.

interface consumoAPi.IQueryString inherits IChaveValor: 
    
     
  
    
    
    

end interface.