
/*------------------------------------------------------------------------
    File        : ETipoRegraNegocio
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : administrator
    Created     : Thu Apr 10 11:04:40 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum RegraNegocio.ETipoRegraNegocio flags :  

    define enum PRIORIDADE 
                AVALIACAO 
                VALIDACAO 
                CALCULO .

end enum.