
DEFINE VARIABLE cCampos{1} AS CHARACTER   NO-UNDO.
DEFINE VARIABLE cArq{1}    AS CHARACTER   NO-UNDO.
ASSIGN cArq{1} = 'c:\temp\{4}.csv'.
OUTPUT TO value(cArq{1}) .    
RUN getCpsTT(TEMP-TABLE {1}:HANDLE,";", OUTPUT cCampos{1}).
PUT UNFORM cCampos{1} SKIP.
FOR EACH {1} {2} NO-LOCK:
    EXPORT DELIMITER ";" {1} {3}.
END.

OUTPUT CLOSE.

OS-COMMAND SILENT VALUE('start ' + carq{1}).

