PROCEDURE setProp:

    DEFINE INPUT  PARAMETER pCampo   AS CHARACTER   NO-UNDO.
    DEFINE INPUT  PARAMETER pPosicao AS INTEGER     NO-UNDO.
    DEFINE INPUT  PARAMETER pValor   AS CHARACTER   NO-UNDO.

    RUN setCpTT(TEMP-TABLE {1}:HANDLE,pCampo,pPosicao,pValor).


END PROCEDURE.
