/*------------------------------------------------------------------------
    File        : EFormaRegistroLog
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : administrator
    Created     : Mon Apr 14 11:21:39 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum Log.EFormaRegistroLog :  

    define enum Posicao 
                Separador .

end enum.