
/*------------------------------------------------------------------------
    File        : EMidiaLog
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : administrator
    Created     : Thu Apr 10 18:19:28 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum Log.EMidiaLog flags :  

    define enum ARQUIVO  = 1
                BANCO_DADOS = 2
                E-MAIL = 4
                APLICATIVO-MSG-INSTANTANEA = 8 
                CONSOLE-WEB = 16
                MSG-TELA = 32.

end enum.