
/*------------------------------------------------------------------------
    File        : ETipoLog
    Purpose     : 
    Syntax      : 
    Description : Níveis de Log
    Author(s)   : administrator
    Created     : Thu Apr 10 15:39:09 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum Log.ETipoLog flags :  

    define enum EMERGENCE 
                ALERT 
                CRITICAL 
                ERRO 
                WARNING 
                NOTICE 
                INFO 
                DEBUG 
                TRACE . 

end enum.