DEFINE VARIABLE cTitulo AS CHARACTER   NO-UNDO FORMAT 'x(100)'.
DEFINE VARIABLE iFornec AS INTEGER     NO-UNDO.
DEFINE VARIABLE cParcela AS CHARACTER   NO-UNDO.

/*


*/
    

REPEAT:
    UPDATE cTitulo iFornec WITH 1 COL WIDTH 550.

    FOR EACH TIT_AP
            WHERE COD_TIT_AP = cTitulo AND CDN_FORNEC =  iFornec AND cod_parcela = cParcela :
        DISP TIT_AP WITH 1 COL WIDTH 550 TITLE "TITULO".
        FOR EACH MOVTO_TIT_AP OF TIT_AP :
            UPDATE MOVTO_TIT_AP WITH 1 COL WIDTH 550 TITLE "MOVIMENTO".
        END.
        FOR EACH PROCES_PAGTO OF TIT_AP:
            UPDATE PROCES_PAGTO WITH 1 COL WIDTH 550 TITLE "PROCESSO PAGTO".
        END.
    END.





END.
