DEFINE VARIABLE ICONT AS INTEGER     NO-UNDO.
DEFINE VARIABLE ICONT2 AS INTEGER     NO-UNDO.
FOR EACH EMITENTE NO-LOCK.
    FIND FIRST EXT-EMITENTE 
        WHERE EMITENTE.COD-EMITENTE  = EXT-EMITENTE.COD-EMITENTE
        AND  EXT-EMITENTE.SITUACAO = 2 NO-LOCK NO-ERROR.
    IF NOT AVAIL EXT-EMITENTE  THEN NEXT.
    ASSIGN ICONT = ICONT + 1.
END.
DISP "TODOS EMITENTES INATIVOS:" ICONT SKIP .


FOR EACH EMITENTE 
    WHERE DATA-IMPLANT >= 01.01.2016 NO-LOCK.
    FIND FIRST EXT-EMITENTE OF EMITENTE
        WHERE EXT-EMITENTE.SITUACAO = 2 NO-LOCK NO-ERROR.
    IF NOT AVAIL EXT-EMITENTE  THEN NEXT.
    ASSIGN ICONT2 = ICONT2 + 1.
END.
DISP "TODOS EMIT.INAT. 01/01/2016:" ICONT2.

