// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void RowErrorsRowChangeEventHandler(object sender, RowErrorsRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class RowErrorsDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnErrorSequence;
            
            private global::System.Data.DataColumn columnErrorNumber;
            
            private global::System.Data.DataColumn columnErrorDescription;
            
            private global::System.Data.DataColumn columnErrorParameters;
            
            private global::System.Data.DataColumn columnErrorType;
            
            private global::System.Data.DataColumn columnErrorHelp;
            
            private global::System.Data.DataColumn columnErrorSubType;
            


            internal void SetRowErrorsOEProps() {
                ProDataTable.SetUserOrder(this.Columns["ErrorSequence"], 0);
                ProDataTable.SetColumnProType(this.Columns["ErrorSequence"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["ErrorNumber"], 1);
                ProDataTable.SetColumnProType(this.Columns["ErrorNumber"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["ErrorDescription"], 2);
                ProDataTable.SetColumnProType(this.Columns["ErrorDescription"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["ErrorParameters"], 3);
                ProDataTable.SetColumnProType(this.Columns["ErrorParameters"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["ErrorType"], 4);
                ProDataTable.SetColumnProType(this.Columns["ErrorType"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["ErrorHelp"], 5);
                ProDataTable.SetColumnProType(this.Columns["ErrorHelp"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["ErrorSubType"], 6);
                ProDataTable.SetColumnProType(this.Columns["ErrorSubType"], Parameter.PRO_CHARACTER);
            }

            public RowErrorsDataTable() {
                this.TableName = "RowErrors";

                this.BeginInit();
                this.InitClass();
                SetRowErrorsOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public RowErrorsDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected RowErrorsDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetRowErrorsOEProps();

            }
            


            public global::System.Data.DataColumn ErrorSequenceColumn {
                get {
                    return this.columnErrorSequence;
                }
            }
            


            public global::System.Data.DataColumn ErrorNumberColumn {
                get {
                    return this.columnErrorNumber;
                }
            }
            


            public global::System.Data.DataColumn ErrorDescriptionColumn {
                get {
                    return this.columnErrorDescription;
                }
            }
            


            public global::System.Data.DataColumn ErrorParametersColumn {
                get {
                    return this.columnErrorParameters;
                }
            }
            


            public global::System.Data.DataColumn ErrorTypeColumn {
                get {
                    return this.columnErrorType;
                }
            }
            


            public global::System.Data.DataColumn ErrorHelpColumn {
                get {
                    return this.columnErrorHelp;
                }
            }
            


            public global::System.Data.DataColumn ErrorSubTypeColumn {
                get {
                    return this.columnErrorSubType;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public RowErrorsRow this[int index] {
                get {
                    return ((RowErrorsRow)(this.Rows[index]));
                }
            }
            

            public event RowErrorsRowChangeEventHandler RowErrorsRowChanging;
            

            public event RowErrorsRowChangeEventHandler RowErrorsRowChanged;
            

            public event RowErrorsRowChangeEventHandler RowErrorsRowDeleting;
            public void Add(System.Object o){}
            

            public event RowErrorsRowChangeEventHandler RowErrorsRowDeleted;
            


            public void AddRowErrorsRow(RowErrorsRow row) {
                this.Rows.Add(row);
            }
            


            public RowErrorsRow AddRowErrorsRow(int ErrorSequence, int ErrorNumber, string ErrorDescription, string ErrorParameters, string ErrorType, string ErrorHelp, string ErrorSubType) {
                RowErrorsRow rowRowErrorsRow = ((RowErrorsRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ErrorSequence,
                        ErrorNumber,
                        ErrorDescription,
                        ErrorParameters,
                        ErrorType,
                        ErrorHelp,
                        ErrorSubType};
                rowRowErrorsRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRowErrorsRow);
                return rowRowErrorsRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                RowErrorsDataTable cln = ((RowErrorsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new RowErrorsDataTable();
            }
            


            internal void InitVars() {
                this.columnErrorSequence = base.Columns["ErrorSequence"];
                this.columnErrorNumber = base.Columns["ErrorNumber"];
                this.columnErrorDescription = base.Columns["ErrorDescription"];
                this.columnErrorParameters = base.Columns["ErrorParameters"];
                this.columnErrorType = base.Columns["ErrorType"];
                this.columnErrorHelp = base.Columns["ErrorHelp"];
                this.columnErrorSubType = base.Columns["ErrorSubType"];
            }
            


            private void InitClass() {
                this.columnErrorSequence = new global::System.Data.DataColumn("ErrorSequence", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnErrorSequence);
                this.columnErrorNumber = new global::System.Data.DataColumn("ErrorNumber", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnErrorNumber);
                this.columnErrorDescription = new global::System.Data.DataColumn("ErrorDescription", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnErrorDescription);
                this.columnErrorParameters = new global::System.Data.DataColumn("ErrorParameters", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnErrorParameters);
                this.columnErrorType = new global::System.Data.DataColumn("ErrorType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnErrorType);
                this.columnErrorHelp = new global::System.Data.DataColumn("ErrorHelp", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnErrorHelp);
                this.columnErrorSubType = new global::System.Data.DataColumn("ErrorSubType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnErrorSubType);
            }
            


            public RowErrorsRow NewRowErrorsRow() {
                return ((RowErrorsRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RowErrorsRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(RowErrorsRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RowErrorsRowChanged != null)) {
                    this.RowErrorsRowChanged(this, new RowErrorsRowChangeEvent(((RowErrorsRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RowErrorsRowChanging != null)) {
                    this.RowErrorsRowChanging(this, new RowErrorsRowChangeEvent(((RowErrorsRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RowErrorsRowDeleted != null)) {
                    this.RowErrorsRowDeleted(this, new RowErrorsRowChangeEvent(((RowErrorsRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RowErrorsRowDeleting != null)) {
                    this.RowErrorsRowDeleting(this, new RowErrorsRowChangeEvent(((RowErrorsRow)(e.Row)), e.Action));
                }
            }
            


            public void RemoveRowErrorsRow(RowErrorsRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class RowErrorsRow : global::System.Data.DataRow {
            
            private RowErrorsDataTable tableRowErrors;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowErrorsRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRowErrors = ((RowErrorsDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ErrorSequence {
                get {
                    try {
                        return ((int)(this[this.tableRowErrors.ErrorSequenceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'ErrorSequence\' na tabela \'RowErrors\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowErrors.ErrorSequenceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ErrorNumber {
                get {
                    try {
                        return ((int)(this[this.tableRowErrors.ErrorNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'ErrorNumber\' na tabela \'RowErrors\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowErrors.ErrorNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ErrorDescription {
                get {
                    try {
                        return ((string)(this[this.tableRowErrors.ErrorDescriptionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'ErrorDescription\' na tabela \'RowErrors\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowErrors.ErrorDescriptionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ErrorParameters {
                get {
                    try {
                        return ((string)(this[this.tableRowErrors.ErrorParametersColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'ErrorParameters\' na tabela \'RowErrors\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowErrors.ErrorParametersColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ErrorType {
                get {
                    try {
                        return ((string)(this[this.tableRowErrors.ErrorTypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'ErrorType\' na tabela \'RowErrors\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowErrors.ErrorTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ErrorHelp {
                get {
                    try {
                        return ((string)(this[this.tableRowErrors.ErrorHelpColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'ErrorHelp\' na tabela \'RowErrors\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowErrors.ErrorHelpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ErrorSubType {
                get {
                    try {
                        return ((string)(this[this.tableRowErrors.ErrorSubTypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'ErrorSubType\' na tabela \'RowErrors\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowErrors.ErrorSubTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsErrorSequenceNull() {
                return this.IsNull(this.tableRowErrors.ErrorSequenceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetErrorSequenceNull() {
                this[this.tableRowErrors.ErrorSequenceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsErrorNumberNull() {
                return this.IsNull(this.tableRowErrors.ErrorNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetErrorNumberNull() {
                this[this.tableRowErrors.ErrorNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsErrorDescriptionNull() {
                return this.IsNull(this.tableRowErrors.ErrorDescriptionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetErrorDescriptionNull() {
                this[this.tableRowErrors.ErrorDescriptionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsErrorParametersNull() {
                return this.IsNull(this.tableRowErrors.ErrorParametersColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetErrorParametersNull() {
                this[this.tableRowErrors.ErrorParametersColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsErrorTypeNull() {
                return this.IsNull(this.tableRowErrors.ErrorTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetErrorTypeNull() {
                this[this.tableRowErrors.ErrorTypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsErrorHelpNull() {
                return this.IsNull(this.tableRowErrors.ErrorHelpColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetErrorHelpNull() {
                this[this.tableRowErrors.ErrorHelpColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsErrorSubTypeNull() {
                return this.IsNull(this.tableRowErrors.ErrorSubTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetErrorSubTypeNull() {
                this[this.tableRowErrors.ErrorSubTypeColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class RowErrorsRowChangeEvent : global::System.EventArgs {
            
            private RowErrorsRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowErrorsRowChangeEvent(RowErrorsRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowErrorsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
