// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void RowInfoRowChangeEventHandler(object sender, RowInfoRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class RowInfoDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnCode;
            
            private global::System.Data.DataColumn columnCodeValue;
            


            internal void SetRowInfoOEProps() {
                ProDataTable.SetUserOrder(this.Columns["Code"], 0);
                ProDataTable.SetColumnProType(this.Columns["Code"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["CodeValue"], 1);
                ProDataTable.SetColumnProType(this.Columns["CodeValue"], Parameter.PRO_CHARACTER);
            }

            public RowInfoDataTable() {
                this.TableName = "RowInfo";

                this.BeginInit();
                this.InitClass();
                SetRowInfoOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public RowInfoDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected RowInfoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetRowInfoOEProps();

            }
            


            public global::System.Data.DataColumn CodeColumn {
                get {
                    return this.columnCode;
                }
            }
            


            public global::System.Data.DataColumn CodeValueColumn {
                get {
                    return this.columnCodeValue;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public RowInfoRow this[int index] {
                get {
                    return ((RowInfoRow)(this.Rows[index]));
                }
            }
            

            public event RowInfoRowChangeEventHandler RowInfoRowChanging;
            

            public event RowInfoRowChangeEventHandler RowInfoRowChanged;
            

            public event RowInfoRowChangeEventHandler RowInfoRowDeleting;
            public void Add(System.Object o){}
            

            public event RowInfoRowChangeEventHandler RowInfoRowDeleted;
            


            public void AddRowInfoRow(RowInfoRow row) {
                this.Rows.Add(row);
            }
            


            public RowInfoRow AddRowInfoRow(string Code, string CodeValue) {
                RowInfoRow rowRowInfoRow = ((RowInfoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Code,
                        CodeValue};
                rowRowInfoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRowInfoRow);
                return rowRowInfoRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                RowInfoDataTable cln = ((RowInfoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new RowInfoDataTable();
            }
            


            internal void InitVars() {
                this.columnCode = base.Columns["Code"];
                this.columnCodeValue = base.Columns["CodeValue"];
            }
            


            private void InitClass() {
                this.columnCode = new global::System.Data.DataColumn("Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCode);
                this.columnCodeValue = new global::System.Data.DataColumn("CodeValue", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCodeValue);
            }
            


            public RowInfoRow NewRowInfoRow() {
                return ((RowInfoRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RowInfoRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(RowInfoRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RowInfoRowChanged != null)) {
                    this.RowInfoRowChanged(this, new RowInfoRowChangeEvent(((RowInfoRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RowInfoRowChanging != null)) {
                    this.RowInfoRowChanging(this, new RowInfoRowChangeEvent(((RowInfoRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RowInfoRowDeleted != null)) {
                    this.RowInfoRowDeleted(this, new RowInfoRowChangeEvent(((RowInfoRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RowInfoRowDeleting != null)) {
                    this.RowInfoRowDeleting(this, new RowInfoRowChangeEvent(((RowInfoRow)(e.Row)), e.Action));
                }
            }
            


            public void RemoveRowInfoRow(RowInfoRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class RowInfoRow : global::System.Data.DataRow {
            
            private RowInfoDataTable tableRowInfo;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowInfoRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRowInfo = ((RowInfoDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Code {
                get {
                    try {
                        return ((string)(this[this.tableRowInfo.CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Code\' na tabela \'RowInfo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowInfo.CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CodeValue {
                get {
                    try {
                        return ((string)(this[this.tableRowInfo.CodeValueColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CodeValue\' na tabela \'RowInfo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowInfo.CodeValueColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCodeNull() {
                return this.IsNull(this.tableRowInfo.CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCodeNull() {
                this[this.tableRowInfo.CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCodeValueNull() {
                return this.IsNull(this.tableRowInfo.CodeValueColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCodeValueNull() {
                this[this.tableRowInfo.CodeValueColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class RowInfoRowChangeEvent : global::System.EventArgs {
            
            private RowInfoRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowInfoRowChangeEvent(RowInfoRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowInfoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
