// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void RowObjectAux2RowChangeEventHandler(object sender, RowObjectAux2RowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class RowObjectAux2DataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn column_r_rowid;
            
            private global::System.Data.DataColumn columncgc;
            
            private global::System.Data.DataColumn column_cod_emitente;
            
            private global::System.Data.DataColumn column_cod_gr_forn;
            
            private global::System.Data.DataColumn columnidentific;
            
            private global::System.Data.DataColumn columnnatureza;
            
            private global::System.Data.DataColumn column_nome_abrev;
            
            private global::System.Data.DataColumn column_nome_emit;
            
            private global::System.Data.DataColumn column_nome_matriz;
            


            internal void SetRowObjectAux2OEProps() {
                ProDataTable.SetUserOrder(this.Columns["r-rowid"], 0);
                ProDataTable.SetColumnProType(this.Columns["r-rowid"], Parameter.PRO_ROWID);
                ProDataTable.SetUserOrder(this.Columns["cgc"], 1);
                ProDataTable.SetColumnProType(this.Columns["cgc"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["cod-emitente"], 2);
                ProDataTable.SetColumnProType(this.Columns["cod-emitente"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["cod-gr-forn"], 3);
                ProDataTable.SetColumnProType(this.Columns["cod-gr-forn"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["identific"], 4);
                ProDataTable.SetColumnProType(this.Columns["identific"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["natureza"], 5);
                ProDataTable.SetColumnProType(this.Columns["natureza"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["nome-abrev"], 6);
                ProDataTable.SetColumnProType(this.Columns["nome-abrev"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["nome-emit"], 7);
                ProDataTable.SetColumnProType(this.Columns["nome-emit"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["nome-matriz"], 8);
                ProDataTable.SetColumnProType(this.Columns["nome-matriz"], Parameter.PRO_CHARACTER);
            }

            public RowObjectAux2DataTable() {
                this.TableName = "RowObjectAux";

                this.BeginInit();
                this.InitClass();
                SetRowObjectAux2OEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public RowObjectAux2DataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected RowObjectAux2DataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetRowObjectAux2OEProps();

            }
            


            public global::System.Data.DataColumn _r_rowidColumn {
                get {
                    return this.column_r_rowid;
                }
            }
            


            public global::System.Data.DataColumn cgcColumn {
                get {
                    return this.columncgc;
                }
            }
            


            public global::System.Data.DataColumn _cod_emitenteColumn {
                get {
                    return this.column_cod_emitente;
                }
            }
            


            public global::System.Data.DataColumn _cod_gr_fornColumn {
                get {
                    return this.column_cod_gr_forn;
                }
            }
            


            public global::System.Data.DataColumn identificColumn {
                get {
                    return this.columnidentific;
                }
            }
            


            public global::System.Data.DataColumn naturezaColumn {
                get {
                    return this.columnnatureza;
                }
            }
            


            public global::System.Data.DataColumn _nome_abrevColumn {
                get {
                    return this.column_nome_abrev;
                }
            }
            


            public global::System.Data.DataColumn _nome_emitColumn {
                get {
                    return this.column_nome_emit;
                }
            }
            


            public global::System.Data.DataColumn _nome_matrizColumn {
                get {
                    return this.column_nome_matriz;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public RowObjectAux2Row this[int index] {
                get {
                    return ((RowObjectAux2Row)(this.Rows[index]));
                }
            }
            

            public event RowObjectAux2RowChangeEventHandler RowObjectAux2RowChanging;
            

            public event RowObjectAux2RowChangeEventHandler RowObjectAux2RowChanged;
            

            public event RowObjectAux2RowChangeEventHandler RowObjectAux2RowDeleting;
            public void Add(System.Object o){}
            

            public event RowObjectAux2RowChangeEventHandler RowObjectAux2RowDeleted;
            


            public void AddRowObjectAux2Row(RowObjectAux2Row row) {
                this.Rows.Add(row);
            }
            


            public RowObjectAux2Row AddRowObjectAux2Row(byte[] _r_rowid, string cgc, int _cod_emitente, int _cod_gr_forn, int identific, int natureza, string _nome_abrev, string _nome_emit, string _nome_matriz) {
                RowObjectAux2Row rowRowObjectAux2Row = ((RowObjectAux2Row)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        _r_rowid,
                        cgc,
                        _cod_emitente,
                        _cod_gr_forn,
                        identific,
                        natureza,
                        _nome_abrev,
                        _nome_emit,
                        _nome_matriz};
                rowRowObjectAux2Row.ItemArray = columnValuesArray;
                this.Rows.Add(rowRowObjectAux2Row);
                return rowRowObjectAux2Row;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                RowObjectAux2DataTable cln = ((RowObjectAux2DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new RowObjectAux2DataTable();
            }
            


            internal void InitVars() {
                this.column_r_rowid = base.Columns["r-rowid"];
                this.columncgc = base.Columns["cgc"];
                this.column_cod_emitente = base.Columns["cod-emitente"];
                this.column_cod_gr_forn = base.Columns["cod-gr-forn"];
                this.columnidentific = base.Columns["identific"];
                this.columnnatureza = base.Columns["natureza"];
                this.column_nome_abrev = base.Columns["nome-abrev"];
                this.column_nome_emit = base.Columns["nome-emit"];
                this.column_nome_matriz = base.Columns["nome-matriz"];
            }
            


            private void InitClass() {
                this.column_r_rowid = new global::System.Data.DataColumn("r-rowid", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_r_rowid);
                this.columncgc = new global::System.Data.DataColumn("cgc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncgc);
                this.column_cod_emitente = new global::System.Data.DataColumn("cod-emitente", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_emitente);
                this.column_cod_gr_forn = new global::System.Data.DataColumn("cod-gr-forn", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_gr_forn);
                this.columnidentific = new global::System.Data.DataColumn("identific", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidentific);
                this.columnnatureza = new global::System.Data.DataColumn("natureza", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnatureza);
                this.column_nome_abrev = new global::System.Data.DataColumn("nome-abrev", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_nome_abrev);
                this.column_nome_emit = new global::System.Data.DataColumn("nome-emit", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_nome_emit);
                this.column_nome_matriz = new global::System.Data.DataColumn("nome-matriz", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_nome_matriz);
            }
            


            public RowObjectAux2Row NewRowObjectAux2Row() {
                return ((RowObjectAux2Row)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RowObjectAux2Row(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(RowObjectAux2Row);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RowObjectAux2RowChanged != null)) {
                    this.RowObjectAux2RowChanged(this, new RowObjectAux2RowChangeEvent(((RowObjectAux2Row)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RowObjectAux2RowChanging != null)) {
                    this.RowObjectAux2RowChanging(this, new RowObjectAux2RowChangeEvent(((RowObjectAux2Row)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RowObjectAux2RowDeleted != null)) {
                    this.RowObjectAux2RowDeleted(this, new RowObjectAux2RowChangeEvent(((RowObjectAux2Row)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RowObjectAux2RowDeleting != null)) {
                    this.RowObjectAux2RowDeleting(this, new RowObjectAux2RowChangeEvent(((RowObjectAux2Row)(e.Row)), e.Action));
                }
            }
            


            public void RemoveRowObjectAux2Row(RowObjectAux2Row row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class RowObjectAux2Row : global::System.Data.DataRow {
            
            private RowObjectAux2DataTable tableRowObjectAux2;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowObjectAux2Row(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRowObjectAux2 = ((RowObjectAux2DataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] _r_rowid {
                get {
                    try {
                        return ((byte[])(this[this.tableRowObjectAux2._r_rowidColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'r-rowid\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2._r_rowidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string cgc {
                get {
                    try {
                        return ((string)(this[this.tableRowObjectAux2.cgcColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cgc\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2.cgcColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _cod_emitente {
                get {
                    try {
                        return ((int)(this[this.tableRowObjectAux2._cod_emitenteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-emitente\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2._cod_emitenteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _cod_gr_forn {
                get {
                    try {
                        return ((int)(this[this.tableRowObjectAux2._cod_gr_fornColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-gr-forn\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2._cod_gr_fornColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int identific {
                get {
                    try {
                        return ((int)(this[this.tableRowObjectAux2.identificColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'identific\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2.identificColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int natureza {
                get {
                    try {
                        return ((int)(this[this.tableRowObjectAux2.naturezaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'natureza\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2.naturezaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _nome_abrev {
                get {
                    try {
                        return ((string)(this[this.tableRowObjectAux2._nome_abrevColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'nome-abrev\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2._nome_abrevColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _nome_emit {
                get {
                    try {
                        return ((string)(this[this.tableRowObjectAux2._nome_emitColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'nome-emit\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2._nome_emitColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _nome_matriz {
                get {
                    try {
                        return ((string)(this[this.tableRowObjectAux2._nome_matrizColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'nome-matriz\' na tabela \'RowObjectAux2\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowObjectAux2._nome_matrizColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_r_rowidNull() {
                return this.IsNull(this.tableRowObjectAux2._r_rowidColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_r_rowidNull() {
                this[this.tableRowObjectAux2._r_rowidColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IscgcNull() {
                return this.IsNull(this.tableRowObjectAux2.cgcColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetcgcNull() {
                this[this.tableRowObjectAux2.cgcColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_emitenteNull() {
                return this.IsNull(this.tableRowObjectAux2._cod_emitenteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_emitenteNull() {
                this[this.tableRowObjectAux2._cod_emitenteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_gr_fornNull() {
                return this.IsNull(this.tableRowObjectAux2._cod_gr_fornColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_gr_fornNull() {
                this[this.tableRowObjectAux2._cod_gr_fornColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsidentificNull() {
                return this.IsNull(this.tableRowObjectAux2.identificColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetidentificNull() {
                this[this.tableRowObjectAux2.identificColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsnaturezaNull() {
                return this.IsNull(this.tableRowObjectAux2.naturezaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetnaturezaNull() {
                this[this.tableRowObjectAux2.naturezaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_nome_abrevNull() {
                return this.IsNull(this.tableRowObjectAux2._nome_abrevColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_nome_abrevNull() {
                this[this.tableRowObjectAux2._nome_abrevColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_nome_emitNull() {
                return this.IsNull(this.tableRowObjectAux2._nome_emitColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_nome_emitNull() {
                this[this.tableRowObjectAux2._nome_emitColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_nome_matrizNull() {
                return this.IsNull(this.tableRowObjectAux2._nome_matrizColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_nome_matrizNull() {
                this[this.tableRowObjectAux2._nome_matrizColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class RowObjectAux2RowChangeEvent : global::System.EventArgs {
            
            private RowObjectAux2Row eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowObjectAux2RowChangeEvent(RowObjectAux2Row row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowObjectAux2Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
