// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void RowRawRowChangeEventHandler(object sender, RowRawRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class RowRawDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnRawRecord;
            


            internal void SetRowRawOEProps() {
                ProDataTable.SetUserOrder(this.Columns["RawRecord"], 0);
                ProDataTable.SetColumnProType(this.Columns["RawRecord"], Parameter.PRO_RAW);
            }

            public RowRawDataTable() {
                this.TableName = "RowRaw";

                this.BeginInit();
                this.InitClass();
                SetRowRawOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public RowRawDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected RowRawDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetRowRawOEProps();

            }
            


            public global::System.Data.DataColumn RawRecordColumn {
                get {
                    return this.columnRawRecord;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public RowRawRow this[int index] {
                get {
                    return ((RowRawRow)(this.Rows[index]));
                }
            }
            

            public event RowRawRowChangeEventHandler RowRawRowChanging;
            

            public event RowRawRowChangeEventHandler RowRawRowChanged;
            

            public event RowRawRowChangeEventHandler RowRawRowDeleting;
            public void Add(System.Object o){}
            

            public event RowRawRowChangeEventHandler RowRawRowDeleted;
            


            public void AddRowRawRow(RowRawRow row) {
                this.Rows.Add(row);
            }
            


            public RowRawRow AddRowRawRow(byte[] RawRecord) {
                RowRawRow rowRowRawRow = ((RowRawRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        RawRecord};
                rowRowRawRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRowRawRow);
                return rowRowRawRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                RowRawDataTable cln = ((RowRawDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new RowRawDataTable();
            }
            


            internal void InitVars() {
                this.columnRawRecord = base.Columns["RawRecord"];
            }
            


            private void InitClass() {
                this.columnRawRecord = new global::System.Data.DataColumn("RawRecord", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRawRecord);
            }
            


            public RowRawRow NewRowRawRow() {
                return ((RowRawRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RowRawRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(RowRawRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RowRawRowChanged != null)) {
                    this.RowRawRowChanged(this, new RowRawRowChangeEvent(((RowRawRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RowRawRowChanging != null)) {
                    this.RowRawRowChanging(this, new RowRawRowChangeEvent(((RowRawRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RowRawRowDeleted != null)) {
                    this.RowRawRowDeleted(this, new RowRawRowChangeEvent(((RowRawRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RowRawRowDeleting != null)) {
                    this.RowRawRowDeleting(this, new RowRawRowChangeEvent(((RowRawRow)(e.Row)), e.Action));
                }
            }
            


            public void RemoveRowRawRow(RowRawRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class RowRawRow : global::System.Data.DataRow {
            
            private RowRawDataTable tableRowRaw;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowRawRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRowRaw = ((RowRawDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] RawRecord {
                get {
                    try {
                        return ((byte[])(this[this.tableRowRaw.RawRecordColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'RawRecord\' na tabela \'RowRaw\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableRowRaw.RawRecordColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRawRecordNull() {
                return this.IsNull(this.tableRowRaw.RawRecordColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRawRecordNull() {
                this[this.tableRowRaw.RawRecordColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class RowRawRowChangeEvent : global::System.EventArgs {
            
            private RowRawRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowRawRowChangeEvent(RowRawRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RowRawRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
