// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttAccountRowChangeEventHandler(object sender, ttAccountRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttAccountDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columncod_pessoa_erp;
            
            private global::System.Data.DataColumn columnnum_id_pessoa;
            


            internal void SetttAccountOEProps() {
                ProDataTable.SetUserOrder(this.Columns["cod_pessoa_erp"], 0);
                ProDataTable.SetColumnProType(this.Columns["cod_pessoa_erp"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["num_id_pessoa"], 1);
                ProDataTable.SetColumnProType(this.Columns["num_id_pessoa"], Parameter.PRO_INTEGER);
            }

            public ttAccountDataTable() {
                this.TableName = "ttAccount";

                this.BeginInit();
                this.InitClass();
                SetttAccountOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttAccountDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttAccountDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttAccountOEProps();

            }
            


            public global::System.Data.DataColumn cod_pessoa_erpColumn {
                get {
                    return this.columncod_pessoa_erp;
                }
            }
            


            public global::System.Data.DataColumn num_id_pessoaColumn {
                get {
                    return this.columnnum_id_pessoa;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttAccountRow this[int index] {
                get {
                    return ((ttAccountRow)(this.Rows[index]));
                }
            }
            

            public event ttAccountRowChangeEventHandler ttAccountRowChanging;
            

            public event ttAccountRowChangeEventHandler ttAccountRowChanged;
            

            public event ttAccountRowChangeEventHandler ttAccountRowDeleting;
            public void Add(System.Object o){}
            

            public event ttAccountRowChangeEventHandler ttAccountRowDeleted;
            


            public void AddttAccountRow(ttAccountRow row) {
                this.Rows.Add(row);
            }
            


            public ttAccountRow AddttAccountRow(string cod_pessoa_erp, int num_id_pessoa) {
                ttAccountRow rowttAccountRow = ((ttAccountRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        cod_pessoa_erp,
                        num_id_pessoa};
                rowttAccountRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttAccountRow);
                return rowttAccountRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttAccountDataTable cln = ((ttAccountDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttAccountDataTable();
            }
            


            internal void InitVars() {
                this.columncod_pessoa_erp = base.Columns["cod_pessoa_erp"];
                this.columnnum_id_pessoa = base.Columns["num_id_pessoa"];
            }
            


            private void InitClass() {
                this.columncod_pessoa_erp = new global::System.Data.DataColumn("cod_pessoa_erp", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncod_pessoa_erp);
                this.columnnum_id_pessoa = new global::System.Data.DataColumn("num_id_pessoa", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnum_id_pessoa);
            }
            


            public ttAccountRow NewttAccountRow() {
                return ((ttAccountRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttAccountRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttAccountRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttAccountRowChanged != null)) {
                    this.ttAccountRowChanged(this, new ttAccountRowChangeEvent(((ttAccountRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttAccountRowChanging != null)) {
                    this.ttAccountRowChanging(this, new ttAccountRowChangeEvent(((ttAccountRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttAccountRowDeleted != null)) {
                    this.ttAccountRowDeleted(this, new ttAccountRowChangeEvent(((ttAccountRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttAccountRowDeleting != null)) {
                    this.ttAccountRowDeleting(this, new ttAccountRowChangeEvent(((ttAccountRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettAccountRow(ttAccountRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttAccountRow : global::System.Data.DataRow {
            
            private ttAccountDataTable tablettAccount;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttAccountRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettAccount = ((ttAccountDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string cod_pessoa_erp {
                get {
                    try {
                        return ((string)(this[this.tablettAccount.cod_pessoa_erpColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod_pessoa_erp\' na tabela \'ttAccount\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettAccount.cod_pessoa_erpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int num_id_pessoa {
                get {
                    try {
                        return ((int)(this[this.tablettAccount.num_id_pessoaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'num_id_pessoa\' na tabela \'ttAccount\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettAccount.num_id_pessoaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscod_pessoa_erpNull() {
                return this.IsNull(this.tablettAccount.cod_pessoa_erpColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcod_pessoa_erpNull() {
                this[this.tablettAccount.cod_pessoa_erpColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnum_id_pessoaNull() {
                return this.IsNull(this.tablettAccount.num_id_pessoaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnum_id_pessoaNull() {
                this[this.tablettAccount.num_id_pessoaColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttAccountRowChangeEvent : global::System.EventArgs {
            
            private ttAccountRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttAccountRowChangeEvent(ttAccountRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttAccountRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
