// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttBoErroRowChangeEventHandler(object sender, ttBoErroRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttBoErroDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn column_i_sequen;
            
            private global::System.Data.DataColumn column_cd_erro;
            
            private global::System.Data.DataColumn columnmensagem;
            
            private global::System.Data.DataColumn columnparametros;
            
            private global::System.Data.DataColumn columnerrortype;
            
            private global::System.Data.DataColumn columnerrorhelp;
            
            private global::System.Data.DataColumn columnerrorsubtype;
            


            internal void SetttBoErroOEProps() {
                ProDataTable.SetUserOrder(this.Columns["i-sequen"], 0);
                ProDataTable.SetColumnProType(this.Columns["i-sequen"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["cd-erro"], 1);
                ProDataTable.SetColumnProType(this.Columns["cd-erro"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["mensagem"], 2);
                ProDataTable.SetColumnProType(this.Columns["mensagem"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["parametros"], 3);
                ProDataTable.SetColumnProType(this.Columns["parametros"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["errortype"], 4);
                ProDataTable.SetColumnProType(this.Columns["errortype"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["errorhelp"], 5);
                ProDataTable.SetColumnProType(this.Columns["errorhelp"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["errorsubtype"], 6);
                ProDataTable.SetColumnProType(this.Columns["errorsubtype"], Parameter.PRO_CHARACTER);
            }

            public ttBoErroDataTable() {
                this.TableName = "tt-bo-erro";

                this.BeginInit();
                this.InitClass();
                SetttBoErroOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttBoErroDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttBoErroDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttBoErroOEProps();

            }
            


            public global::System.Data.DataColumn _i_sequenColumn {
                get {
                    return this.column_i_sequen;
                }
            }
            


            public global::System.Data.DataColumn _cd_erroColumn {
                get {
                    return this.column_cd_erro;
                }
            }
            


            public global::System.Data.DataColumn mensagemColumn {
                get {
                    return this.columnmensagem;
                }
            }
            


            public global::System.Data.DataColumn parametrosColumn {
                get {
                    return this.columnparametros;
                }
            }
            


            public global::System.Data.DataColumn errortypeColumn {
                get {
                    return this.columnerrortype;
                }
            }
            


            public global::System.Data.DataColumn errorhelpColumn {
                get {
                    return this.columnerrorhelp;
                }
            }
            


            public global::System.Data.DataColumn errorsubtypeColumn {
                get {
                    return this.columnerrorsubtype;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttBoErroRow this[int index] {
                get {
                    return ((ttBoErroRow)(this.Rows[index]));
                }
            }
            

            public event ttBoErroRowChangeEventHandler ttBoErroRowChanging;
            

            public event ttBoErroRowChangeEventHandler ttBoErroRowChanged;
            

            public event ttBoErroRowChangeEventHandler ttBoErroRowDeleting;
            public void Add(System.Object o){}
            

            public event ttBoErroRowChangeEventHandler ttBoErroRowDeleted;
            


            public void AddttBoErroRow(ttBoErroRow row) {
                this.Rows.Add(row);
            }
            


            public ttBoErroRow AddttBoErroRow(int _i_sequen, int _cd_erro, string mensagem, string parametros, string errortype, string errorhelp, string errorsubtype) {
                ttBoErroRow rowttBoErroRow = ((ttBoErroRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        _i_sequen,
                        _cd_erro,
                        mensagem,
                        parametros,
                        errortype,
                        errorhelp,
                        errorsubtype};
                rowttBoErroRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttBoErroRow);
                return rowttBoErroRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttBoErroDataTable cln = ((ttBoErroDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttBoErroDataTable();
            }
            


            internal void InitVars() {
                this.column_i_sequen = base.Columns["i-sequen"];
                this.column_cd_erro = base.Columns["cd-erro"];
                this.columnmensagem = base.Columns["mensagem"];
                this.columnparametros = base.Columns["parametros"];
                this.columnerrortype = base.Columns["errortype"];
                this.columnerrorhelp = base.Columns["errorhelp"];
                this.columnerrorsubtype = base.Columns["errorsubtype"];
            }
            


            private void InitClass() {
                this.column_i_sequen = new global::System.Data.DataColumn("i-sequen", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_i_sequen);
                this.column_cd_erro = new global::System.Data.DataColumn("cd-erro", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cd_erro);
                this.columnmensagem = new global::System.Data.DataColumn("mensagem", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmensagem);
                this.columnparametros = new global::System.Data.DataColumn("parametros", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnparametros);
                this.columnerrortype = new global::System.Data.DataColumn("errortype", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnerrortype);
                this.columnerrorhelp = new global::System.Data.DataColumn("errorhelp", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnerrorhelp);
                this.columnerrorsubtype = new global::System.Data.DataColumn("errorsubtype", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnerrorsubtype);
            }
            


            public ttBoErroRow NewttBoErroRow() {
                return ((ttBoErroRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttBoErroRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttBoErroRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttBoErroRowChanged != null)) {
                    this.ttBoErroRowChanged(this, new ttBoErroRowChangeEvent(((ttBoErroRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttBoErroRowChanging != null)) {
                    this.ttBoErroRowChanging(this, new ttBoErroRowChangeEvent(((ttBoErroRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttBoErroRowDeleted != null)) {
                    this.ttBoErroRowDeleted(this, new ttBoErroRowChangeEvent(((ttBoErroRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttBoErroRowDeleting != null)) {
                    this.ttBoErroRowDeleting(this, new ttBoErroRowChangeEvent(((ttBoErroRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettBoErroRow(ttBoErroRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttBoErroRow : global::System.Data.DataRow {
            
            private ttBoErroDataTable tablettBoErro;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttBoErroRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettBoErro = ((ttBoErroDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _i_sequen {
                get {
                    try {
                        return ((int)(this[this.tablettBoErro._i_sequenColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'i-sequen\' na tabela \'ttBoErro\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettBoErro._i_sequenColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _cd_erro {
                get {
                    try {
                        return ((int)(this[this.tablettBoErro._cd_erroColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cd-erro\' na tabela \'ttBoErro\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettBoErro._cd_erroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string mensagem {
                get {
                    try {
                        return ((string)(this[this.tablettBoErro.mensagemColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'mensagem\' na tabela \'ttBoErro\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettBoErro.mensagemColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string parametros {
                get {
                    try {
                        return ((string)(this[this.tablettBoErro.parametrosColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'parametros\' na tabela \'ttBoErro\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettBoErro.parametrosColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string errortype {
                get {
                    try {
                        return ((string)(this[this.tablettBoErro.errortypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'errortype\' na tabela \'ttBoErro\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettBoErro.errortypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string errorhelp {
                get {
                    try {
                        return ((string)(this[this.tablettBoErro.errorhelpColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'errorhelp\' na tabela \'ttBoErro\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettBoErro.errorhelpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string errorsubtype {
                get {
                    try {
                        return ((string)(this[this.tablettBoErro.errorsubtypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'errorsubtype\' na tabela \'ttBoErro\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettBoErro.errorsubtypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_i_sequenNull() {
                return this.IsNull(this.tablettBoErro._i_sequenColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_i_sequenNull() {
                this[this.tablettBoErro._i_sequenColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cd_erroNull() {
                return this.IsNull(this.tablettBoErro._cd_erroColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cd_erroNull() {
                this[this.tablettBoErro._cd_erroColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsmensagemNull() {
                return this.IsNull(this.tablettBoErro.mensagemColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetmensagemNull() {
                this[this.tablettBoErro.mensagemColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsparametrosNull() {
                return this.IsNull(this.tablettBoErro.parametrosColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetparametrosNull() {
                this[this.tablettBoErro.parametrosColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IserrortypeNull() {
                return this.IsNull(this.tablettBoErro.errortypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SeterrortypeNull() {
                this[this.tablettBoErro.errortypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IserrorhelpNull() {
                return this.IsNull(this.tablettBoErro.errorhelpColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SeterrorhelpNull() {
                this[this.tablettBoErro.errorhelpColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IserrorsubtypeNull() {
                return this.IsNull(this.tablettBoErro.errorsubtypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SeterrorsubtypeNull() {
                this[this.tablettBoErro.errorsubtypeColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttBoErroRowChangeEvent : global::System.EventArgs {
            
            private ttBoErroRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttBoErroRowChangeEvent(ttBoErroRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttBoErroRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
