// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttCtaPagarRecRowChangeEventHandler(object sender, ttCtaPagarRecRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttCtaPagarRecDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn column_da_maior;
            
            private global::System.Data.DataColumn column_de_vl_maior;
            
            private global::System.Data.DataColumn column_da_ultimo;
            
            private global::System.Data.DataColumn column_de_vl_ultimo;
            
            private global::System.Data.DataColumn column_i_atraso_medio;
            
            private global::System.Data.DataColumn column_r_rowid;
            


            internal void SetttCtaPagarRecOEProps() {
                ProDataTable.SetUserOrder(this.Columns["da-maior"], 0);
                ProDataTable.SetColumnProType(this.Columns["da-maior"], Parameter.PRO_DATE);
                ProDataTable.SetUserOrder(this.Columns["de-vl-maior"], 1);
                ProDataTable.SetColumnProType(this.Columns["de-vl-maior"], Parameter.PRO_DECIMAL);
                ProDataTable.SetUserOrder(this.Columns["da-ultimo"], 2);
                ProDataTable.SetColumnProType(this.Columns["da-ultimo"], Parameter.PRO_DATE);
                ProDataTable.SetUserOrder(this.Columns["de-vl-ultimo"], 3);
                ProDataTable.SetColumnProType(this.Columns["de-vl-ultimo"], Parameter.PRO_DECIMAL);
                ProDataTable.SetUserOrder(this.Columns["i-atraso-medio"], 4);
                ProDataTable.SetColumnProType(this.Columns["i-atraso-medio"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["r-rowid"], 5);
                ProDataTable.SetColumnProType(this.Columns["r-rowid"], Parameter.PRO_ROWID);
            }

            public ttCtaPagarRecDataTable() {
                this.TableName = "tt-cta-pagar-rec";

                this.BeginInit();
                this.InitClass();
                SetttCtaPagarRecOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttCtaPagarRecDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttCtaPagarRecDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttCtaPagarRecOEProps();

            }
            


            public global::System.Data.DataColumn _da_maiorColumn {
                get {
                    return this.column_da_maior;
                }
            }
            


            public global::System.Data.DataColumn _de_vl_maiorColumn {
                get {
                    return this.column_de_vl_maior;
                }
            }
            


            public global::System.Data.DataColumn _da_ultimoColumn {
                get {
                    return this.column_da_ultimo;
                }
            }
            


            public global::System.Data.DataColumn _de_vl_ultimoColumn {
                get {
                    return this.column_de_vl_ultimo;
                }
            }
            


            public global::System.Data.DataColumn _i_atraso_medioColumn {
                get {
                    return this.column_i_atraso_medio;
                }
            }
            


            public global::System.Data.DataColumn _r_rowidColumn {
                get {
                    return this.column_r_rowid;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttCtaPagarRecRow this[int index] {
                get {
                    return ((ttCtaPagarRecRow)(this.Rows[index]));
                }
            }
            

            public event ttCtaPagarRecRowChangeEventHandler ttCtaPagarRecRowChanging;
            

            public event ttCtaPagarRecRowChangeEventHandler ttCtaPagarRecRowChanged;
            

            public event ttCtaPagarRecRowChangeEventHandler ttCtaPagarRecRowDeleting;
            public void Add(System.Object o){}
            

            public event ttCtaPagarRecRowChangeEventHandler ttCtaPagarRecRowDeleted;
            


            public void AddttCtaPagarRecRow(ttCtaPagarRecRow row) {
                this.Rows.Add(row);
            }
            


            public ttCtaPagarRecRow AddttCtaPagarRecRow(System.DateTime _da_maior, decimal _de_vl_maior, System.DateTime _da_ultimo, decimal _de_vl_ultimo, int _i_atraso_medio, byte[] _r_rowid) {
                ttCtaPagarRecRow rowttCtaPagarRecRow = ((ttCtaPagarRecRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        _da_maior,
                        _de_vl_maior,
                        _da_ultimo,
                        _de_vl_ultimo,
                        _i_atraso_medio,
                        _r_rowid};
                rowttCtaPagarRecRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttCtaPagarRecRow);
                return rowttCtaPagarRecRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttCtaPagarRecDataTable cln = ((ttCtaPagarRecDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttCtaPagarRecDataTable();
            }
            


            internal void InitVars() {
                this.column_da_maior = base.Columns["da-maior"];
                this.column_de_vl_maior = base.Columns["de-vl-maior"];
                this.column_da_ultimo = base.Columns["da-ultimo"];
                this.column_de_vl_ultimo = base.Columns["de-vl-ultimo"];
                this.column_i_atraso_medio = base.Columns["i-atraso-medio"];
                this.column_r_rowid = base.Columns["r-rowid"];
            }
            


            private void InitClass() {
                this.column_da_maior = new global::System.Data.DataColumn("da-maior", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_da_maior);
                this.column_de_vl_maior = new global::System.Data.DataColumn("de-vl-maior", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_de_vl_maior);
                this.column_da_ultimo = new global::System.Data.DataColumn("da-ultimo", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_da_ultimo);
                this.column_de_vl_ultimo = new global::System.Data.DataColumn("de-vl-ultimo", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_de_vl_ultimo);
                this.column_i_atraso_medio = new global::System.Data.DataColumn("i-atraso-medio", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_i_atraso_medio);
                this.column_r_rowid = new global::System.Data.DataColumn("r-rowid", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_r_rowid);
            }
            


            public ttCtaPagarRecRow NewttCtaPagarRecRow() {
                return ((ttCtaPagarRecRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttCtaPagarRecRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttCtaPagarRecRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttCtaPagarRecRowChanged != null)) {
                    this.ttCtaPagarRecRowChanged(this, new ttCtaPagarRecRowChangeEvent(((ttCtaPagarRecRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttCtaPagarRecRowChanging != null)) {
                    this.ttCtaPagarRecRowChanging(this, new ttCtaPagarRecRowChangeEvent(((ttCtaPagarRecRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttCtaPagarRecRowDeleted != null)) {
                    this.ttCtaPagarRecRowDeleted(this, new ttCtaPagarRecRowChangeEvent(((ttCtaPagarRecRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttCtaPagarRecRowDeleting != null)) {
                    this.ttCtaPagarRecRowDeleting(this, new ttCtaPagarRecRowChangeEvent(((ttCtaPagarRecRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettCtaPagarRecRow(ttCtaPagarRecRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttCtaPagarRecRow : global::System.Data.DataRow {
            
            private ttCtaPagarRecDataTable tablettCtaPagarRec;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttCtaPagarRecRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettCtaPagarRec = ((ttCtaPagarRecDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime _da_maior {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablettCtaPagarRec._da_maiorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'da-maior\' na tabela \'ttCtaPagarRec\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettCtaPagarRec._da_maiorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal _de_vl_maior {
                get {
                    try {
                        return ((decimal)(this[this.tablettCtaPagarRec._de_vl_maiorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'de-vl-maior\' na tabela \'ttCtaPagarRec\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettCtaPagarRec._de_vl_maiorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime _da_ultimo {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablettCtaPagarRec._da_ultimoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'da-ultimo\' na tabela \'ttCtaPagarRec\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettCtaPagarRec._da_ultimoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal _de_vl_ultimo {
                get {
                    try {
                        return ((decimal)(this[this.tablettCtaPagarRec._de_vl_ultimoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'de-vl-ultimo\' na tabela \'ttCtaPagarRec\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettCtaPagarRec._de_vl_ultimoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _i_atraso_medio {
                get {
                    try {
                        return ((int)(this[this.tablettCtaPagarRec._i_atraso_medioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'i-atraso-medio\' na tabela \'ttCtaPagarRec\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettCtaPagarRec._i_atraso_medioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] _r_rowid {
                get {
                    try {
                        return ((byte[])(this[this.tablettCtaPagarRec._r_rowidColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'r-rowid\' na tabela \'ttCtaPagarRec\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettCtaPagarRec._r_rowidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_da_maiorNull() {
                return this.IsNull(this.tablettCtaPagarRec._da_maiorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_da_maiorNull() {
                this[this.tablettCtaPagarRec._da_maiorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_de_vl_maiorNull() {
                return this.IsNull(this.tablettCtaPagarRec._de_vl_maiorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_de_vl_maiorNull() {
                this[this.tablettCtaPagarRec._de_vl_maiorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_da_ultimoNull() {
                return this.IsNull(this.tablettCtaPagarRec._da_ultimoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_da_ultimoNull() {
                this[this.tablettCtaPagarRec._da_ultimoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_de_vl_ultimoNull() {
                return this.IsNull(this.tablettCtaPagarRec._de_vl_ultimoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_de_vl_ultimoNull() {
                this[this.tablettCtaPagarRec._de_vl_ultimoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_i_atraso_medioNull() {
                return this.IsNull(this.tablettCtaPagarRec._i_atraso_medioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_i_atraso_medioNull() {
                this[this.tablettCtaPagarRec._i_atraso_medioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_r_rowidNull() {
                return this.IsNull(this.tablettCtaPagarRec._r_rowidColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_r_rowidNull() {
                this[this.tablettCtaPagarRec._r_rowidColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttCtaPagarRecRowChangeEvent : global::System.EventArgs {
            
            private ttCtaPagarRecRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttCtaPagarRecRowChangeEvent(ttCtaPagarRecRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttCtaPagarRecRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
