// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttCta_canal_clienRowChangeEventHandler(object sender, ttCta_canal_clienRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttCta_canal_clienDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columncod_pessoa_erp;
            


            internal void SetttCta_canal_clienOEProps() {
                ProDataTable.SetUserOrder(this.Columns["cod_pessoa_erp"], 0);
                ProDataTable.SetColumnProType(this.Columns["cod_pessoa_erp"], Parameter.PRO_CHARACTER);
            }

            public ttCta_canal_clienDataTable() {
                this.TableName = "tt-cta_canal_clien";

                this.BeginInit();
                this.InitClass();
                SetttCta_canal_clienOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttCta_canal_clienDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttCta_canal_clienDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttCta_canal_clienOEProps();

            }
            


            public global::System.Data.DataColumn cod_pessoa_erpColumn {
                get {
                    return this.columncod_pessoa_erp;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttCta_canal_clienRow this[int index] {
                get {
                    return ((ttCta_canal_clienRow)(this.Rows[index]));
                }
            }
            

            public event ttCta_canal_clienRowChangeEventHandler ttCta_canal_clienRowChanging;
            

            public event ttCta_canal_clienRowChangeEventHandler ttCta_canal_clienRowChanged;
            

            public event ttCta_canal_clienRowChangeEventHandler ttCta_canal_clienRowDeleting;
            public void Add(System.Object o){}
            

            public event ttCta_canal_clienRowChangeEventHandler ttCta_canal_clienRowDeleted;
            


            public void AddttCta_canal_clienRow(ttCta_canal_clienRow row) {
                this.Rows.Add(row);
            }
            


            public ttCta_canal_clienRow AddttCta_canal_clienRow(string cod_pessoa_erp) {
                ttCta_canal_clienRow rowttCta_canal_clienRow = ((ttCta_canal_clienRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        cod_pessoa_erp};
                rowttCta_canal_clienRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttCta_canal_clienRow);
                return rowttCta_canal_clienRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttCta_canal_clienDataTable cln = ((ttCta_canal_clienDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttCta_canal_clienDataTable();
            }
            


            internal void InitVars() {
                this.columncod_pessoa_erp = base.Columns["cod_pessoa_erp"];
            }
            


            private void InitClass() {
                this.columncod_pessoa_erp = new global::System.Data.DataColumn("cod_pessoa_erp", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncod_pessoa_erp);
            }
            


            public ttCta_canal_clienRow NewttCta_canal_clienRow() {
                return ((ttCta_canal_clienRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttCta_canal_clienRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttCta_canal_clienRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttCta_canal_clienRowChanged != null)) {
                    this.ttCta_canal_clienRowChanged(this, new ttCta_canal_clienRowChangeEvent(((ttCta_canal_clienRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttCta_canal_clienRowChanging != null)) {
                    this.ttCta_canal_clienRowChanging(this, new ttCta_canal_clienRowChangeEvent(((ttCta_canal_clienRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttCta_canal_clienRowDeleted != null)) {
                    this.ttCta_canal_clienRowDeleted(this, new ttCta_canal_clienRowChangeEvent(((ttCta_canal_clienRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttCta_canal_clienRowDeleting != null)) {
                    this.ttCta_canal_clienRowDeleting(this, new ttCta_canal_clienRowChangeEvent(((ttCta_canal_clienRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettCta_canal_clienRow(ttCta_canal_clienRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttCta_canal_clienRow : global::System.Data.DataRow {
            
            private ttCta_canal_clienDataTable tablettCta_canal_clien;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttCta_canal_clienRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettCta_canal_clien = ((ttCta_canal_clienDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string cod_pessoa_erp {
                get {
                    try {
                        return ((string)(this[this.tablettCta_canal_clien.cod_pessoa_erpColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod_pessoa_erp\' na tabela \'ttCta_canal_clien\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettCta_canal_clien.cod_pessoa_erpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscod_pessoa_erpNull() {
                return this.IsNull(this.tablettCta_canal_clien.cod_pessoa_erpColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcod_pessoa_erpNull() {
                this[this.tablettCta_canal_clien.cod_pessoa_erpColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttCta_canal_clienRowChangeEvent : global::System.EventArgs {
            
            private ttCta_canal_clienRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttCta_canal_clienRowChangeEvent(ttCta_canal_clienRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttCta_canal_clienRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
