// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttGrupoClienteRowChangeEventHandler(object sender, ttGrupoClienteRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttGrupoClienteDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columncodgrcli;
            


            internal void SetttGrupoClienteOEProps() {
                ProDataTable.SetUserOrder(this.Columns["codgrcli"], 0);
                ProDataTable.SetColumnProType(this.Columns["codgrcli"], Parameter.PRO_CHARACTER);
            }

            public ttGrupoClienteDataTable() {
                this.TableName = "ttGrupoCliente";

                this.BeginInit();
                this.InitClass();
                SetttGrupoClienteOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttGrupoClienteDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttGrupoClienteDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttGrupoClienteOEProps();

            }
            


            public global::System.Data.DataColumn codgrcliColumn {
                get {
                    return this.columncodgrcli;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttGrupoClienteRow this[int index] {
                get {
                    return ((ttGrupoClienteRow)(this.Rows[index]));
                }
            }
            

            public event ttGrupoClienteRowChangeEventHandler ttGrupoClienteRowChanging;
            

            public event ttGrupoClienteRowChangeEventHandler ttGrupoClienteRowChanged;
            

            public event ttGrupoClienteRowChangeEventHandler ttGrupoClienteRowDeleting;
            public void Add(System.Object o){}
            

            public event ttGrupoClienteRowChangeEventHandler ttGrupoClienteRowDeleted;
            


            public void AddttGrupoClienteRow(ttGrupoClienteRow row) {
                this.Rows.Add(row);
            }
            


            public ttGrupoClienteRow AddttGrupoClienteRow(string codgrcli) {
                ttGrupoClienteRow rowttGrupoClienteRow = ((ttGrupoClienteRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        codgrcli};
                rowttGrupoClienteRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttGrupoClienteRow);
                return rowttGrupoClienteRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttGrupoClienteDataTable cln = ((ttGrupoClienteDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttGrupoClienteDataTable();
            }
            


            internal void InitVars() {
                this.columncodgrcli = base.Columns["codgrcli"];
            }
            


            private void InitClass() {
                this.columncodgrcli = new global::System.Data.DataColumn("codgrcli", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodgrcli);
            }
            


            public ttGrupoClienteRow NewttGrupoClienteRow() {
                return ((ttGrupoClienteRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttGrupoClienteRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttGrupoClienteRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttGrupoClienteRowChanged != null)) {
                    this.ttGrupoClienteRowChanged(this, new ttGrupoClienteRowChangeEvent(((ttGrupoClienteRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttGrupoClienteRowChanging != null)) {
                    this.ttGrupoClienteRowChanging(this, new ttGrupoClienteRowChangeEvent(((ttGrupoClienteRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttGrupoClienteRowDeleted != null)) {
                    this.ttGrupoClienteRowDeleted(this, new ttGrupoClienteRowChangeEvent(((ttGrupoClienteRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttGrupoClienteRowDeleting != null)) {
                    this.ttGrupoClienteRowDeleting(this, new ttGrupoClienteRowChangeEvent(((ttGrupoClienteRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettGrupoClienteRow(ttGrupoClienteRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttGrupoClienteRow : global::System.Data.DataRow {
            
            private ttGrupoClienteDataTable tablettGrupoCliente;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttGrupoClienteRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettGrupoCliente = ((ttGrupoClienteDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string codgrcli {
                get {
                    try {
                        return ((string)(this[this.tablettGrupoCliente.codgrcliColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'codgrcli\' na tabela \'ttGrupoCliente\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettGrupoCliente.codgrcliColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IscodgrcliNull() {
                return this.IsNull(this.tablettGrupoCliente.codgrcliColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetcodgrcliNull() {
                this[this.tablettGrupoCliente.codgrcliColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttGrupoClienteRowChangeEvent : global::System.EventArgs {
            
            private ttGrupoClienteRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttGrupoClienteRowChangeEvent(ttGrupoClienteRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttGrupoClienteRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
