// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttListaRowidRowChangeEventHandler(object sender, ttListaRowidRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttListaRowidDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnuid;
            


            internal void SetttListaRowidOEProps() {
                ProDataTable.SetUserOrder(this.Columns["uid"], 0);
                ProDataTable.SetColumnProType(this.Columns["uid"], Parameter.PRO_CHARACTER);
            }

            public ttListaRowidDataTable() {
                this.TableName = "ttListaRowid";

                this.BeginInit();
                this.InitClass();
                SetttListaRowidOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttListaRowidDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttListaRowidDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttListaRowidOEProps();

            }
            


            public global::System.Data.DataColumn uidColumn {
                get {
                    return this.columnuid;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttListaRowidRow this[int index] {
                get {
                    return ((ttListaRowidRow)(this.Rows[index]));
                }
            }
            

            public event ttListaRowidRowChangeEventHandler ttListaRowidRowChanging;
            

            public event ttListaRowidRowChangeEventHandler ttListaRowidRowChanged;
            

            public event ttListaRowidRowChangeEventHandler ttListaRowidRowDeleting;
            public void Add(System.Object o){}
            

            public event ttListaRowidRowChangeEventHandler ttListaRowidRowDeleted;
            


            public void AddttListaRowidRow(ttListaRowidRow row) {
                this.Rows.Add(row);
            }
            


            public ttListaRowidRow AddttListaRowidRow(string uid) {
                ttListaRowidRow rowttListaRowidRow = ((ttListaRowidRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        uid};
                rowttListaRowidRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttListaRowidRow);
                return rowttListaRowidRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttListaRowidDataTable cln = ((ttListaRowidDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttListaRowidDataTable();
            }
            


            internal void InitVars() {
                this.columnuid = base.Columns["uid"];
            }
            


            private void InitClass() {
                this.columnuid = new global::System.Data.DataColumn("uid", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnuid);
            }
            


            public ttListaRowidRow NewttListaRowidRow() {
                return ((ttListaRowidRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttListaRowidRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttListaRowidRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttListaRowidRowChanged != null)) {
                    this.ttListaRowidRowChanged(this, new ttListaRowidRowChangeEvent(((ttListaRowidRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttListaRowidRowChanging != null)) {
                    this.ttListaRowidRowChanging(this, new ttListaRowidRowChangeEvent(((ttListaRowidRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttListaRowidRowDeleted != null)) {
                    this.ttListaRowidRowDeleted(this, new ttListaRowidRowChangeEvent(((ttListaRowidRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttListaRowidRowDeleting != null)) {
                    this.ttListaRowidRowDeleting(this, new ttListaRowidRowChangeEvent(((ttListaRowidRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettListaRowidRow(ttListaRowidRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttListaRowidRow : global::System.Data.DataRow {
            
            private ttListaRowidDataTable tablettListaRowid;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttListaRowidRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettListaRowid = ((ttListaRowidDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string uid {
                get {
                    try {
                        return ((string)(this[this.tablettListaRowid.uidColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'uid\' na tabela \'ttListaRowid\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettListaRowid.uidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsuidNull() {
                return this.IsNull(this.tablettListaRowid.uidColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetuidNull() {
                this[this.tablettListaRowid.uidColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttListaRowidRowChangeEvent : global::System.EventArgs {
            
            private ttListaRowidRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttListaRowidRowChangeEvent(ttListaRowidRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttListaRowidRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
