// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttMaqEpEstAuxRowChangeEventHandler(object sender, ttMaqEpEstAuxRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttMaqEpEstAuxDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn column_cd_maquina;
            
            private global::System.Data.DataColumn column_ep_codigo;
            
            private global::System.Data.DataColumn column_cod_estabel;
            
            private global::System.Data.DataColumn column_tp_conexao;
            


            internal void SetttMaqEpEstAuxOEProps() {
                ProDataTable.SetUserOrder(this.Columns["cd-maquina"], 0);
                ProDataTable.SetColumnProType(this.Columns["cd-maquina"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["ep-codigo"], 1);
                ProDataTable.SetColumnProType(this.Columns["ep-codigo"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["cod-estabel"], 2);
                ProDataTable.SetColumnProType(this.Columns["cod-estabel"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["tp-conexao"], 3);
                ProDataTable.SetColumnProType(this.Columns["tp-conexao"], Parameter.PRO_INTEGER);
            }

            public ttMaqEpEstAuxDataTable() {
                this.TableName = "tt-maq-ep-est-aux";

                this.BeginInit();
                this.InitClass();
                SetttMaqEpEstAuxOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttMaqEpEstAuxDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttMaqEpEstAuxDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttMaqEpEstAuxOEProps();

            }
            


            public global::System.Data.DataColumn _cd_maquinaColumn {
                get {
                    return this.column_cd_maquina;
                }
            }
            


            public global::System.Data.DataColumn _ep_codigoColumn {
                get {
                    return this.column_ep_codigo;
                }
            }
            


            public global::System.Data.DataColumn _cod_estabelColumn {
                get {
                    return this.column_cod_estabel;
                }
            }
            


            public global::System.Data.DataColumn _tp_conexaoColumn {
                get {
                    return this.column_tp_conexao;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttMaqEpEstAuxRow this[int index] {
                get {
                    return ((ttMaqEpEstAuxRow)(this.Rows[index]));
                }
            }
            

            public event ttMaqEpEstAuxRowChangeEventHandler ttMaqEpEstAuxRowChanging;
            

            public event ttMaqEpEstAuxRowChangeEventHandler ttMaqEpEstAuxRowChanged;
            

            public event ttMaqEpEstAuxRowChangeEventHandler ttMaqEpEstAuxRowDeleting;
            public void Add(System.Object o){}
            

            public event ttMaqEpEstAuxRowChangeEventHandler ttMaqEpEstAuxRowDeleted;
            


            public void AddttMaqEpEstAuxRow(ttMaqEpEstAuxRow row) {
                this.Rows.Add(row);
            }
            


            public ttMaqEpEstAuxRow AddttMaqEpEstAuxRow(int _cd_maquina, string _ep_codigo, string _cod_estabel, int _tp_conexao) {
                ttMaqEpEstAuxRow rowttMaqEpEstAuxRow = ((ttMaqEpEstAuxRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        _cd_maquina,
                        _ep_codigo,
                        _cod_estabel,
                        _tp_conexao};
                rowttMaqEpEstAuxRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttMaqEpEstAuxRow);
                return rowttMaqEpEstAuxRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttMaqEpEstAuxDataTable cln = ((ttMaqEpEstAuxDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttMaqEpEstAuxDataTable();
            }
            


            internal void InitVars() {
                this.column_cd_maquina = base.Columns["cd-maquina"];
                this.column_ep_codigo = base.Columns["ep-codigo"];
                this.column_cod_estabel = base.Columns["cod-estabel"];
                this.column_tp_conexao = base.Columns["tp-conexao"];
            }
            


            private void InitClass() {
                this.column_cd_maquina = new global::System.Data.DataColumn("cd-maquina", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cd_maquina);
                this.column_ep_codigo = new global::System.Data.DataColumn("ep-codigo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_ep_codigo);
                this.column_cod_estabel = new global::System.Data.DataColumn("cod-estabel", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_estabel);
                this.column_tp_conexao = new global::System.Data.DataColumn("tp-conexao", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_tp_conexao);
            }
            


            public ttMaqEpEstAuxRow NewttMaqEpEstAuxRow() {
                return ((ttMaqEpEstAuxRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttMaqEpEstAuxRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttMaqEpEstAuxRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttMaqEpEstAuxRowChanged != null)) {
                    this.ttMaqEpEstAuxRowChanged(this, new ttMaqEpEstAuxRowChangeEvent(((ttMaqEpEstAuxRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttMaqEpEstAuxRowChanging != null)) {
                    this.ttMaqEpEstAuxRowChanging(this, new ttMaqEpEstAuxRowChangeEvent(((ttMaqEpEstAuxRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttMaqEpEstAuxRowDeleted != null)) {
                    this.ttMaqEpEstAuxRowDeleted(this, new ttMaqEpEstAuxRowChangeEvent(((ttMaqEpEstAuxRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttMaqEpEstAuxRowDeleting != null)) {
                    this.ttMaqEpEstAuxRowDeleting(this, new ttMaqEpEstAuxRowChangeEvent(((ttMaqEpEstAuxRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettMaqEpEstAuxRow(ttMaqEpEstAuxRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttMaqEpEstAuxRow : global::System.Data.DataRow {
            
            private ttMaqEpEstAuxDataTable tablettMaqEpEstAux;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttMaqEpEstAuxRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettMaqEpEstAux = ((ttMaqEpEstAuxDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _cd_maquina {
                get {
                    try {
                        return ((int)(this[this.tablettMaqEpEstAux._cd_maquinaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cd-maquina\' na tabela \'ttMaqEpEstAux\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettMaqEpEstAux._cd_maquinaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _ep_codigo {
                get {
                    try {
                        return ((string)(this[this.tablettMaqEpEstAux._ep_codigoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'ep-codigo\' na tabela \'ttMaqEpEstAux\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettMaqEpEstAux._ep_codigoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _cod_estabel {
                get {
                    try {
                        return ((string)(this[this.tablettMaqEpEstAux._cod_estabelColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-estabel\' na tabela \'ttMaqEpEstAux\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettMaqEpEstAux._cod_estabelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _tp_conexao {
                get {
                    try {
                        return ((int)(this[this.tablettMaqEpEstAux._tp_conexaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'tp-conexao\' na tabela \'ttMaqEpEstAux\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettMaqEpEstAux._tp_conexaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cd_maquinaNull() {
                return this.IsNull(this.tablettMaqEpEstAux._cd_maquinaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cd_maquinaNull() {
                this[this.tablettMaqEpEstAux._cd_maquinaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_ep_codigoNull() {
                return this.IsNull(this.tablettMaqEpEstAux._ep_codigoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_ep_codigoNull() {
                this[this.tablettMaqEpEstAux._ep_codigoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_estabelNull() {
                return this.IsNull(this.tablettMaqEpEstAux._cod_estabelColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_estabelNull() {
                this[this.tablettMaqEpEstAux._cod_estabelColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_tp_conexaoNull() {
                return this.IsNull(this.tablettMaqEpEstAux._tp_conexaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_tp_conexaoNull() {
                this[this.tablettMaqEpEstAux._tp_conexaoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttMaqEpEstAuxRowChangeEvent : global::System.EventArgs {
            
            private ttMaqEpEstAuxRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttMaqEpEstAuxRowChangeEvent(ttMaqEpEstAuxRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttMaqEpEstAuxRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
