// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttParamRowChangeEventHandler(object sender, ttParamRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttParamDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn column_cod_estab_ini;
            
            private global::System.Data.DataColumn column_cod_estab_fim;
            
            private global::System.Data.DataColumn column_cod_esp_ini;
            
            private global::System.Data.DataColumn column_cod_esp_fim;
            
            private global::System.Data.DataColumn column_cod_port_ini;
            
            private global::System.Data.DataColumn column_cod_port_fim;
            
            private global::System.Data.DataColumn column_dt_emissao_ini;
            
            private global::System.Data.DataColumn column_dt_emissao_fim;
            


            internal void SetttParamOEProps() {
                ProDataTable.SetUserOrder(this.Columns["cod-estab-ini"], 0);
                ProDataTable.SetColumnProType(this.Columns["cod-estab-ini"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["cod-estab-fim"], 1);
                ProDataTable.SetColumnProType(this.Columns["cod-estab-fim"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["cod-esp-ini"], 2);
                ProDataTable.SetColumnProType(this.Columns["cod-esp-ini"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["cod-esp-fim"], 3);
                ProDataTable.SetColumnProType(this.Columns["cod-esp-fim"], Parameter.PRO_CHARACTER);
                ProDataTable.SetUserOrder(this.Columns["cod-port-ini"], 4);
                ProDataTable.SetColumnProType(this.Columns["cod-port-ini"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["cod-port-fim"], 5);
                ProDataTable.SetColumnProType(this.Columns["cod-port-fim"], Parameter.PRO_INTEGER);
                ProDataTable.SetUserOrder(this.Columns["dt-emissao-ini"], 6);
                ProDataTable.SetColumnProType(this.Columns["dt-emissao-ini"], Parameter.PRO_DATE);
                ProDataTable.SetUserOrder(this.Columns["dt-emissao-fim"], 7);
                ProDataTable.SetColumnProType(this.Columns["dt-emissao-fim"], Parameter.PRO_DATE);
            }

            public ttParamDataTable() {
                this.TableName = "tt-param";

                this.BeginInit();
                this.InitClass();
                SetttParamOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttParamDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttParamDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttParamOEProps();

            }
            


            public global::System.Data.DataColumn _cod_estab_iniColumn {
                get {
                    return this.column_cod_estab_ini;
                }
            }
            


            public global::System.Data.DataColumn _cod_estab_fimColumn {
                get {
                    return this.column_cod_estab_fim;
                }
            }
            


            public global::System.Data.DataColumn _cod_esp_iniColumn {
                get {
                    return this.column_cod_esp_ini;
                }
            }
            


            public global::System.Data.DataColumn _cod_esp_fimColumn {
                get {
                    return this.column_cod_esp_fim;
                }
            }
            


            public global::System.Data.DataColumn _cod_port_iniColumn {
                get {
                    return this.column_cod_port_ini;
                }
            }
            


            public global::System.Data.DataColumn _cod_port_fimColumn {
                get {
                    return this.column_cod_port_fim;
                }
            }
            


            public global::System.Data.DataColumn _dt_emissao_iniColumn {
                get {
                    return this.column_dt_emissao_ini;
                }
            }
            


            public global::System.Data.DataColumn _dt_emissao_fimColumn {
                get {
                    return this.column_dt_emissao_fim;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttParamRow this[int index] {
                get {
                    return ((ttParamRow)(this.Rows[index]));
                }
            }
            

            public event ttParamRowChangeEventHandler ttParamRowChanging;
            

            public event ttParamRowChangeEventHandler ttParamRowChanged;
            

            public event ttParamRowChangeEventHandler ttParamRowDeleting;
            public void Add(System.Object o){}
            

            public event ttParamRowChangeEventHandler ttParamRowDeleted;
            


            public void AddttParamRow(ttParamRow row) {
                this.Rows.Add(row);
            }
            


            public ttParamRow AddttParamRow(string _cod_estab_ini, string _cod_estab_fim, string _cod_esp_ini, string _cod_esp_fim, int _cod_port_ini, int _cod_port_fim, System.DateTime _dt_emissao_ini, System.DateTime _dt_emissao_fim) {
                ttParamRow rowttParamRow = ((ttParamRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        _cod_estab_ini,
                        _cod_estab_fim,
                        _cod_esp_ini,
                        _cod_esp_fim,
                        _cod_port_ini,
                        _cod_port_fim,
                        _dt_emissao_ini,
                        _dt_emissao_fim};
                rowttParamRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttParamRow);
                return rowttParamRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttParamDataTable cln = ((ttParamDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttParamDataTable();
            }
            


            internal void InitVars() {
                this.column_cod_estab_ini = base.Columns["cod-estab-ini"];
                this.column_cod_estab_fim = base.Columns["cod-estab-fim"];
                this.column_cod_esp_ini = base.Columns["cod-esp-ini"];
                this.column_cod_esp_fim = base.Columns["cod-esp-fim"];
                this.column_cod_port_ini = base.Columns["cod-port-ini"];
                this.column_cod_port_fim = base.Columns["cod-port-fim"];
                this.column_dt_emissao_ini = base.Columns["dt-emissao-ini"];
                this.column_dt_emissao_fim = base.Columns["dt-emissao-fim"];
            }
            


            private void InitClass() {
                this.column_cod_estab_ini = new global::System.Data.DataColumn("cod-estab-ini", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_estab_ini);
                this.column_cod_estab_fim = new global::System.Data.DataColumn("cod-estab-fim", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_estab_fim);
                this.column_cod_esp_ini = new global::System.Data.DataColumn("cod-esp-ini", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_esp_ini);
                this.column_cod_esp_fim = new global::System.Data.DataColumn("cod-esp-fim", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_esp_fim);
                this.column_cod_port_ini = new global::System.Data.DataColumn("cod-port-ini", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_port_ini);
                this.column_cod_port_fim = new global::System.Data.DataColumn("cod-port-fim", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_cod_port_fim);
                this.column_dt_emissao_ini = new global::System.Data.DataColumn("dt-emissao-ini", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_dt_emissao_ini);
                this.column_dt_emissao_fim = new global::System.Data.DataColumn("dt-emissao-fim", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.column_dt_emissao_fim);
            }
            


            public ttParamRow NewttParamRow() {
                return ((ttParamRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttParamRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttParamRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttParamRowChanged != null)) {
                    this.ttParamRowChanged(this, new ttParamRowChangeEvent(((ttParamRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttParamRowChanging != null)) {
                    this.ttParamRowChanging(this, new ttParamRowChangeEvent(((ttParamRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttParamRowDeleted != null)) {
                    this.ttParamRowDeleted(this, new ttParamRowChangeEvent(((ttParamRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttParamRowDeleting != null)) {
                    this.ttParamRowDeleting(this, new ttParamRowChangeEvent(((ttParamRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettParamRow(ttParamRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttParamRow : global::System.Data.DataRow {
            
            private ttParamDataTable tablettParam;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttParamRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettParam = ((ttParamDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _cod_estab_ini {
                get {
                    try {
                        return ((string)(this[this.tablettParam._cod_estab_iniColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-estab-ini\' na tabela \'ttParam\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettParam._cod_estab_iniColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _cod_estab_fim {
                get {
                    try {
                        return ((string)(this[this.tablettParam._cod_estab_fimColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-estab-fim\' na tabela \'ttParam\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettParam._cod_estab_fimColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _cod_esp_ini {
                get {
                    try {
                        return ((string)(this[this.tablettParam._cod_esp_iniColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-esp-ini\' na tabela \'ttParam\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettParam._cod_esp_iniColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string _cod_esp_fim {
                get {
                    try {
                        return ((string)(this[this.tablettParam._cod_esp_fimColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-esp-fim\' na tabela \'ttParam\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettParam._cod_esp_fimColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _cod_port_ini {
                get {
                    try {
                        return ((int)(this[this.tablettParam._cod_port_iniColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-port-ini\' na tabela \'ttParam\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettParam._cod_port_iniColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _cod_port_fim {
                get {
                    try {
                        return ((int)(this[this.tablettParam._cod_port_fimColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod-port-fim\' na tabela \'ttParam\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettParam._cod_port_fimColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime _dt_emissao_ini {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablettParam._dt_emissao_iniColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'dt-emissao-ini\' na tabela \'ttParam\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettParam._dt_emissao_iniColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime _dt_emissao_fim {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablettParam._dt_emissao_fimColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'dt-emissao-fim\' na tabela \'ttParam\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettParam._dt_emissao_fimColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_estab_iniNull() {
                return this.IsNull(this.tablettParam._cod_estab_iniColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_estab_iniNull() {
                this[this.tablettParam._cod_estab_iniColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_estab_fimNull() {
                return this.IsNull(this.tablettParam._cod_estab_fimColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_estab_fimNull() {
                this[this.tablettParam._cod_estab_fimColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_esp_iniNull() {
                return this.IsNull(this.tablettParam._cod_esp_iniColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_esp_iniNull() {
                this[this.tablettParam._cod_esp_iniColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_esp_fimNull() {
                return this.IsNull(this.tablettParam._cod_esp_fimColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_esp_fimNull() {
                this[this.tablettParam._cod_esp_fimColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_port_iniNull() {
                return this.IsNull(this.tablettParam._cod_port_iniColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_port_iniNull() {
                this[this.tablettParam._cod_port_iniColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_cod_port_fimNull() {
                return this.IsNull(this.tablettParam._cod_port_fimColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_cod_port_fimNull() {
                this[this.tablettParam._cod_port_fimColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_dt_emissao_iniNull() {
                return this.IsNull(this.tablettParam._dt_emissao_iniColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_dt_emissao_iniNull() {
                this[this.tablettParam._dt_emissao_iniColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_dt_emissao_fimNull() {
                return this.IsNull(this.tablettParam._dt_emissao_fimColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_dt_emissao_fimNull() {
                this[this.tablettParam._dt_emissao_fimColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttParamRowChangeEvent : global::System.EventArgs {
            
            private ttParamRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttParamRowChangeEvent(ttParamRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttParamRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
