// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StrongTypesNS {
    
        using Progress.Open4GL;

        public delegate void ttReg_cta_erpRowChangeEventHandler(object sender, ttReg_cta_erpRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [global::System.ComponentModel.DesignerCategoryAttribute("code")]
        [global::System.ComponentModel.ToolboxItem(true)]
        public partial class ttReg_cta_erpDataTable : ProDataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columncod_mic_reg;
            


            internal void SetttReg_cta_erpOEProps() {
                ProDataTable.SetUserOrder(this.Columns["cod_mic_reg"], 0);
                ProDataTable.SetColumnProType(this.Columns["cod_mic_reg"], Parameter.PRO_CHARACTER);
            }

            public ttReg_cta_erpDataTable() {
                this.TableName = "tt-reg_cta_erp";

                this.BeginInit();
                this.InitClass();
                SetttReg_cta_erpOEProps();
                this.Namespace = this.TableName + "NS";
                this.EndInit();
            }
            


            public ttReg_cta_erpDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            


            protected ttReg_cta_erpDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
                SetttReg_cta_erpOEProps();

            }
            


            public global::System.Data.DataColumn cod_mic_regColumn {
                get {
                    return this.columncod_mic_reg;
                }
            }
            


            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            


            public ttReg_cta_erpRow this[int index] {
                get {
                    return ((ttReg_cta_erpRow)(this.Rows[index]));
                }
            }
            

            public event ttReg_cta_erpRowChangeEventHandler ttReg_cta_erpRowChanging;
            

            public event ttReg_cta_erpRowChangeEventHandler ttReg_cta_erpRowChanged;
            

            public event ttReg_cta_erpRowChangeEventHandler ttReg_cta_erpRowDeleting;
            public void Add(System.Object o){}
            

            public event ttReg_cta_erpRowChangeEventHandler ttReg_cta_erpRowDeleted;
            


            public void AddttReg_cta_erpRow(ttReg_cta_erpRow row) {
                this.Rows.Add(row);
            }
            


            public ttReg_cta_erpRow AddttReg_cta_erpRow(string cod_mic_reg) {
                ttReg_cta_erpRow rowttReg_cta_erpRow = ((ttReg_cta_erpRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        cod_mic_reg};
                rowttReg_cta_erpRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowttReg_cta_erpRow);
                return rowttReg_cta_erpRow;
            }
            


            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            


            public override global::System.Data.DataTable Clone() {
                ttReg_cta_erpDataTable cln = ((ttReg_cta_erpDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            


            protected override global::System.Data.DataTable CreateInstance() {
                return new ttReg_cta_erpDataTable();
            }
            


            internal void InitVars() {
                this.columncod_mic_reg = base.Columns["cod_mic_reg"];
            }
            


            private void InitClass() {
                this.columncod_mic_reg = new global::System.Data.DataColumn("cod_mic_reg", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncod_mic_reg);
            }
            


            public ttReg_cta_erpRow NewttReg_cta_erpRow() {
                return ((ttReg_cta_erpRow)(this.NewRow()));
            }
            


            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ttReg_cta_erpRow(builder);
            }
            


            protected override global::System.Type GetRowType() {
                return typeof(ttReg_cta_erpRow);
            }
            


            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ttReg_cta_erpRowChanged != null)) {
                    this.ttReg_cta_erpRowChanged(this, new ttReg_cta_erpRowChangeEvent(((ttReg_cta_erpRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ttReg_cta_erpRowChanging != null)) {
                    this.ttReg_cta_erpRowChanging(this, new ttReg_cta_erpRowChangeEvent(((ttReg_cta_erpRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ttReg_cta_erpRowDeleted != null)) {
                    this.ttReg_cta_erpRowDeleted(this, new ttReg_cta_erpRowChangeEvent(((ttReg_cta_erpRow)(e.Row)), e.Action));
                }
            }
            


            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ttReg_cta_erpRowDeleting != null)) {
                    this.ttReg_cta_erpRowDeleting(this, new ttReg_cta_erpRowChangeEvent(((ttReg_cta_erpRow)(e.Row)), e.Action));
                }
            }
            


            public void RemovettReg_cta_erpRow(ttReg_cta_erpRow row) {
                this.Rows.Remove(row);
            }
            



        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ttReg_cta_erpRow : global::System.Data.DataRow {
            
            private ttReg_cta_erpDataTable tablettReg_cta_erp;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttReg_cta_erpRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablettReg_cta_erp = ((ttReg_cta_erpDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string cod_mic_reg {
                get {
                    try {
                        return ((string)(this[this.tablettReg_cta_erp.cod_mic_regColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'cod_mic_reg\' na tabela \'ttReg_cta_erp\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tablettReg_cta_erp.cod_mic_regColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscod_mic_regNull() {
                return this.IsNull(this.tablettReg_cta_erp.cod_mic_regColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcod_mic_regNull() {
                this[this.tablettReg_cta_erp.cod_mic_regColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class ttReg_cta_erpRowChangeEvent : global::System.EventArgs {
            
            private ttReg_cta_erpRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttReg_cta_erpRowChangeEvent(ttReg_cta_erpRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public ttReg_cta_erpRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
