/* EMS 2 */
CREATE ALIAS mgadm   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgdis   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgfis   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgcld   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgcex   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mginv   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgind   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgmfg   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgmnt   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgmrp   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgscm   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgdbr   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS emsdca  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS ems2oe  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mgsop   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS mguni   FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS movadm  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS movdis  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS movfis  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS movind  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS movmfg  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS movmnt  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS movdbr  FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS wmovdis FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS ems2ima FOR DATABASE ems2 NO-ERROR.
CREATE ALIAS ems2med FOR DATABASE ems2 NO-ERROR.

/*Financeiro*/
CREATE ALIAS emsbas  FOR DATABASE ems5  NO-ERROR.
CREATE ALIAS emsedi  FOR DATABASE ems5  NO-ERROR.
CREATE ALIAS emsfin  FOR DATABASE ems5  NO-ERROR.
CREATE ALIAS emsuni  FOR DATABASE ems5  NO-ERROR.
CREATE ALIAS emsven  FOR DATABASE ems5  NO-ERROR.
CREATE ALIAS emsnam  FOR DATABASE ems5  NO-ERROR.
CREATE ALIAS movfin  FOR DATABASE ems5  NO-ERROR.

/*
FIND FIRST para-ped NO-LOCK NO-ERROR.
OUTPUT TO c:\temp\ALIAS.txt.
   PUT  CONNECTED("ems2") SKIP
        para-ped.estab-padrao SKIP.
OUTPUT CLOSE.
*/

