DEFINE INPUT  PARAMETER cRef    AS CHARACTER   NO-UNDO.
DEFINE OUTPUT PARAMETER ordem   AS INTEGER     NO-UNDO.
DEFINE VARIABLE cInicio         AS CHARACTER   NO-UNDO.
DEFINE VARIABLE cResto          AS CHARACTER   NO-UNDO.
DEFINE VARIABLE somaResto       AS INT     NO-UNDO.
DEFINE VARIABLE iCont           AS INTEGER     NO-UNDO.
DEFINE VARIABLE iAscLetra       AS INTEGER     NO-UNDO.
DEFINE VARIABLE cLetra          AS CHARACTER   NO-UNDO.
DEFINE VARIABLE lZeroEsquerda   AS LOGICAL INIT YES     NO-UNDO.
DEFINE VARIABLE iTesteNum       AS INTEGER     NO-UNDO.

ASSIGN cInicio = SUBSTRING(cRef,1,1)
       cResto  = SUBSTRING(cRef,2,LENGTH(cRef) - 1).

ASSIGN iTesteNum = INT(cResto) NO-ERROR.
IF NOT ERROR-STATUS:ERROR  THEN
   ASSIGN  ordem   = ASC(upper(cInicio)) * 100000 + INT(cResto) .


