DEFINE INPUT  PARAMETER pValor AS CHARACTER FORMAT 'x(10000)'   NO-UNDO.
DEFINE INPUT  PARAMETER pIncr  AS CHARACTER FORMAT 'x(100)'   NO-UNDO.
DEFINE INPUT  PARAMETER pDelimitador AS CHARACTER   NO-UNDO.
DEFINE OUTPUT PARAMETER cNovoValor AS CHARACTER   NO-UNDO.

IF pValor = '' THEN
   ASSIGN cNovoValor = pIncr.
ELSE
  ASSIGN cNovoValor  = pValor + pDelimitador + pIncr.




