DEFINE VARIABLE i-handle  AS INTEGER NO-UNDO.

PROCEDURE FindWindowA EXTERNAL "USER32.DLL":
    DEFINE INPUT  PARAMETER intClassName AS LONG.
    DEFINE INPUT  PARAMETER chrCaption   AS CHARACTER.
    DEFINE RETURN PARAMETER intHandle    AS LONG.
END PROCEDURE.

REPEAT.
 RUN FindWindowA (0, "Calculadora", OUTPUT i-handle).
 IF i-handle = 0 THEN LEAVE.
END. 

MESSAGE 'sai' VIEW-AS ALERT-BOX.
