DEF VAR sBuffer  AS CHAR FORMAT "x(256)" NO-UNDO.
DEF VAR lSize    AS INT INIT 255.


RUN GetUserNameA (OUTPUT sBuffer, INPUT-OUTPUT lSize).

MESSAGE sBuffer
    VIEW-AS ALERT-BOX INFO BUTTONS OK.


PROCEDURE GetUserNameA EXTERNAL "advapi32.dll":
    DEFINE OUTPUT       PARAMETER lpBuffer  AS CHARACTER.
    DEFINE INPUT-OUTPUT PARAMETER nSize AS LONG.
END PROCEDURE.

