
/*------------------------------------------------------------------------
    File        : EConvCodPag
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : user
    Created     : Mon Apr 21 12:50:16 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum Arquivo.EConvCodPag :  

    define enum iso-8859-1_utf-8 
                utf-8_iso-8859-1 
                iso-8859-1_ibm850 
                ibm850_iso-8859-1
                NAO-CONVERTER .

end enum.