
/*------------------------------------------------------------------------
    File        : EDelimitador
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : user
    Created     : Mon Apr 21 12:03:25 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum Arquivo.EDelimitador :  

    define enum VIRGULA
                PONTO-VIRGULA
                PIPE
                DOIS-PONTOS
                BARRA-PARA-DIREITA
                BARRA-PARA-ESQUERDA
                SINAL-DE-IGUAL
                HIFEN
                .
                
                
                

end enum.