
/*------------------------------------------------------------------------
    File        : ETipoZArquivo
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : user
    Created     : Tue Apr 15 14:21:35 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum Arquivo.ETipoArquivo flags :  

    define enum TEXTO-LIVRE 
                JSON 
                XML 
                IMAGEM 
                CSV 
                TEXTO-COM-SEPARADOR 
                EXCEL 
                WORD 
                PDF 
                RTF .

end enum.