DEFINE INPUT  PARAMETER cData AS CHARACTER   NO-UNDO.
DEFINE OUTPUT PARAMETER data  AS DATE        NO-UNDO.

DEFINE VARIABLE cMes  AS CHARACTER   NO-UNDO.
DEFINE VARIABLE cAno  AS CHARACTER   NO-UNDO.
DEFINE VARIABLE cDia  AS CHARACTER   NO-UNDO.

ASSIGN  cMes = SUBSTRING(cData,6,2)
        cAno = SUBSTRING(cData,1,4)
        cDia = SUBSTRING(cData,9,2)
        data = DATE(INT(cMes),INT(cDia),INT(cAno)).


