
/*------------------------------------------------------------------------
    File        : EMedidaTempo
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : administrator
    Created     : Thu Apr 10 18:12:19 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

enum EMedidaTempo flags :  

    define enum SEGUNDO 
                MINUTO 
                HORA 
                DIA 
                MES 
                BIMESTRE 
                TRIMESTRE 
                QUADRIMESTRE 
                SEMESTRE 
                ANO 
                QUINQUENIO 
                DECADA 
                SECULO 
                MILENIO .

end enum.