
/*------------------------------------------------------------------------
    File        : IColecao
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : administrator
    Created     : Mon Apr 14 12:29:30 BRT 2025
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface IColecao:  
    
    define public property obj as Object no-undo 
    get.
    set. 
    
    method public void _criarTT( ).   
   
       
    
    
    
    
  
end interface.